# Generated by Django 5.2.17 on 2026-08-26 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='issueauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_encrypted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sha256_hash',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_encrypted',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sha256_hash',
        ),
        migrations.RemoveField(
            model_name='issueauditlog',
            name='sha256_hash',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_issues', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('STORY', 'Story'), ('TASK', 'Task'), ('BUG', 'Bug'), ('EPIC', 'Epic'), ('IMPROVEMENT', 'Improvement')], default='TASK', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(default='120 KB', max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('BLOCKS', 'Blocks'), ('IS_BLOCKED_BY', 'Is Blocked By'), ('RELATES_TO', 'Relates To'), ('DUPLICATES', 'Duplicates')], default='RELATES_TO', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='issues.issue')),
                ('target_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='issues.issue')),
            ],
            options={
                'unique_together': {('source_issue', 'target_issue', 'link_type')},
            },
        ),
    ]
