# Generated by Django 5.2.17 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_avatar_color_project_category_project_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Project Owner'), ('MANAGER', 'Project Manager / Scrum Master'), ('DEVELOPER', 'Software Developer'), ('TESTER', 'QA / Tester'), ('VIEWER', 'Viewer')], default='DEVELOPER', max_length=20),
        ),
    ]
