# Generated by Django 5.2.17 on 2026-08-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(default=100, help_text='Composite score 0-100')),
                ('status_label', models.CharField(choices=[('HEALTHY', 'Healthy (Optimal Velocity)'), ('MODERATE_RISK', 'Moderate Risk (Attention Required)'), ('CRITICAL_RISK', 'Critical Risk (Sprint Target in Jeopardy)')], default='HEALTHY', max_length=30)),
                ('burndown_score', models.IntegerField(default=100)),
                ('scope_creep_score', models.IntegerField(default=100)),
                ('bottleneck_score', models.IntegerField(default=100)),
                ('workload_score', models.IntegerField(default=100)),
                ('completion_probability', models.IntegerField(default=95)),
                ('diagnostics_json', models.TextField(blank=True, default='[]')),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='sprints.sprint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
