# Generated by Django 5.2.17 on 2026-08-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_avatar_color_project_category_project_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sprint_number', models.PositiveIntegerField(default=1)),
                ('goal', models.TextField(blank=True, help_text='Core objective and deliverables for this sprint')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning / Future'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_committed_points', models.IntegerField(default=0)),
                ('completed_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
            options={
                'ordering': ['-sprint_number', '-created_at'],
            },
        ),
    ]
