# Generated by Django 5.2.17 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Project Manager / Scrum Master'), ('DEVELOPER', 'Software Engineer'), ('TESTER', 'QA / Test Engineer'), ('VIEWER', 'Stakeholder / Viewer')], default='DEVELOPER', max_length=30),
        ),
    ]
