# Generated by Django 5.2.17 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_encrypted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sha256_hash',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Issue Assigned'), ('STATUS_CHANGE', 'Status Changed'), ('COMMENT', 'New Comment'), ('MENTION', 'User Mentioned'), ('SPRINT_STARTED', 'Sprint Started'), ('SPRINT_COMPLETED', 'Sprint Completed'), ('DUE_DATE_APPROACHING', 'Due Date Approaching'), ('PROJECT_INVITATION', 'Project Invitation'), ('SYSTEM', 'System Update')], default='SYSTEM', max_length=30),
        ),
    ]
