# Generated by Django 5.2.17 on 2026-08-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_chatmessage_is_encrypted_and_more'),
        ('projects', '0003_alter_project_avatar_color_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation_role',
            field=models.CharField(blank=True, default='DEVELOPER', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='invitation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_notifications', to='projects.project'),
        ),
    ]
