# Generated by Django 5.2.17 on 2026-09-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_invitation_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamroom',
            name='project',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='TeamRoom',
        ),
    ]
